import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Home1</Link>
        </li>
        <li>
          <Link to="/frame6415">Frame6415</Link>
        </li>
        <li>
          <Link to="/slide169one">Slide169One</Link>
        </li>
        <li>
          <Link to="/aboutus">AboutUS</Link>
        </li>
        <li>
          <Link to="/services">Services</Link>
        </li>
        <li>
          <Link to="/gallery">Gallery</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/blogone">BlogOne</Link>
        </li>
        <li>
          <Link to="/teamone">TeamOne</Link>
        </li>
        <li>
          <Link to="/team">Team</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
